/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul Marx (https://sketchfab.com/PaulMarx)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/garden-house-forbidden-city-beijing-china-7vq3SGtUxHmOSmxU7qkl63JKVbc
Title: Garden House, Forbidden City, Beijing, China
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useScroll, useTime, useTransform } from "framer-motion";
import { useFrame } from "@react-three/fiber";

export function Model() {
  const ref = useRef(null);
  const { nodes, materials } = useGLTF("./model.glb") as any;
  const { scrollYProgress } = useScroll();
  const yAngle = useTransform(scrollYProgress, [0, 1], [-9, 9]);

  useFrame(({ camera }) => {
    camera.position.setFromSphericalCoords(yAngle.get(), yAngle.get(), 0);
    camera.updateProjectionMatrix();
  });

  return (
    <group ref={ref} position={[2, 0, -2]} dispose={null}>
      <points
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
      />
      <points
        geometry={nodes.Object_3.geometry}
        material={materials["Scene_-_Root"]}
      />
      <points
        geometry={nodes.Object_4.geometry}
        material={materials["Scene_-_Root"]}
      />
      <points
        geometry={nodes.Object_5.geometry}
        material={materials["Scene_-_Root"]}
      />
      <points
        geometry={nodes.Object_6.geometry}
        material={materials["Scene_-_Root"]}
      />
    </group>
  );
}

useGLTF.preload("./model.glb");
